#! /users/ke2mcbri/www/app/bin/python
import argparse

from db.models import Song, Chart, Score, connect_to_db


ACTIONS = ['create', 'drop']
TABLES = [Song, Chart, Score] # in order of dependency

if __name__ == '__main__':
    ap = argparse.ArgumentParser()
    ap.add_argument('action', choices=ACTIONS)
    args = ap.parse_args()

    db = connect_to_db()
    if args.action == 'create':
        with db.atomic():
            db.create_tables(TABLES)

    elif args.action == 'drop':
        with db.atomic():
            # reversed to be careful about dependency
            db.drop_tables(TABLES[::-1])
